# Welcome to Jekyll!
#

# Site settings
title: Moratoria
description: | Frente a la turistizaci√≥n de la ciudad de Madrid - Parar, pensar y actuar. 
owner: Moratoria # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: hola@moratoria.eu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://moratoria.eu/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/moratoria_
  github: https://github.com/moratoria
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:hola@moratoria.eu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
